version: "3.9"
services:
  db:
    container_name: feedmaker_db
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feedmaker_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    tty: true
    container_name: feedmaker_api
    build:
        context: .
        dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=feedmaker_db
      - DB_SSLMODE=disable
      - PORT=8080

volumes:
  db_data:
